#! sh

#xiec.drv
#setcon /dev/xiec

#con.drv
con80.drv -b

echo Init V1.0 starting

xiec.drv
pipe.drv > /dev/xiec
pty.drv
tcpip.drv 
digi.drv
uart.drv

#ppp /dev/xiec
#gui

sh -t /dev/con81 &
sh -t /dev/con82 &
sh -t /dev/con83 &
sh -t /dev/con84 &
sh -t /dev/con2 &
sh -t /dev/con3 &
sh -t /dev/con4 &
echo
echo [For help, type: more help.txt]
echo
exec sh
