#! sh

mkdir usr/bin
mkdir usr/drivers
mkdir usr/libs
mkdir usr/fonts
mkdir usr/inet
mv cat hexdump kill mem more si wc connect echo initp ls memchk ps shot test usr/bin
cp sh usr/bin
mv con.drv con80.drv cbmfsys.drv idefsys.drv digi.drv xiec.drv tcpip.drv pty.drv iec.drv win.drv vicii.drv ide.drv usr/drivers
mv libc.so crt.so serlib.so fontlib.so fsyslib.so winlib.so conlib.so usr/libs
mv system.8p usr/fonts
mv httpd irc slip ppp telnet telnetd web ajirc usr/inet
