#! sh

#xiec.drv
#setcon /dev/xiec

#con.drv
con80.drv -b
setcon /dev/con1

echo Init V1.0 starting

#gui
#exit
#winapp
#stars
xiec.drv
pty.drv
tcpip.drv 
ppp /dev/xiec
digi.drv
#uart.drv
#connect /dev/modem 
telnetd
httpd
#gui

sh -c /dev/con81 &
sh -c /dev/con82 &
sh -c /dev/con2 &
sh -c /dev/con3 &
sh -c /dev/con4 &
echo
echo [For help, type: more help.txt]
echo
sh &
exit
